// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDcpEiYk8CESqJLJjEq2Qkg3zXD2RuWmRY',
    appId: '1:525479710922:web:1ceb9761e252bdc508e433',
    messagingSenderId: '525479710922',
    projectId: 'the-employee-6d783',
    authDomain: 'the-employee-6d783.firebaseapp.com',
    storageBucket: 'the-employee-6d783.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXc7CZKYg0o0g3R832ivRLe5aLsQ1Vfrk',
    appId: '1:525479710922:android:1da5f2ec0e2a888708e433',
    messagingSenderId: '525479710922',
    projectId: 'the-employee-6d783',
    storageBucket: 'the-employee-6d783.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAl-snXhfjcmwicaNRrISVHmUO6aXUCxWg',
    appId: '1:525479710922:ios:b463ac9e04cba8a208e433',
    messagingSenderId: '525479710922',
    projectId: 'the-employee-6d783',
    storageBucket: 'the-employee-6d783.appspot.com',
    iosBundleId: 'com.example.theEmployee',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAl-snXhfjcmwicaNRrISVHmUO6aXUCxWg',
    appId: '1:525479710922:ios:dc4d5a25370cba6c08e433',
    messagingSenderId: '525479710922',
    projectId: 'the-employee-6d783',
    storageBucket: 'the-employee-6d783.appspot.com',
    iosBundleId: 'com.example.theEmployee.RunnerTests',
  );
}
