// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAtuYMTJtL7g1Gjlh1-Fge6ufY0faxttSQ',
    appId: '1:666637684350:web:1cedfc4fdfb7c28e16522f',
    messagingSenderId: '666637684350',
    projectId: 'the-expenses-718d1',
    authDomain: 'the-expenses-718d1.firebaseapp.com',
    storageBucket: 'the-expenses-718d1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB51BSKg3SXzs1beQBOnH2kut-siS3ZbP8',
    appId: '1:666637684350:android:a3dfafd8a92673bb16522f',
    messagingSenderId: '666637684350',
    projectId: 'the-expenses-718d1',
    storageBucket: 'the-expenses-718d1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6sBZzO7jMc7aDFhAKZsnYlNNvp1jS_Aw',
    appId: '1:666637684350:ios:51cb45e93ef1389d16522f',
    messagingSenderId: '666637684350',
    projectId: 'the-expenses-718d1',
    storageBucket: 'the-expenses-718d1.appspot.com',
    iosBundleId: 'com.example.theExpenses',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD6sBZzO7jMc7aDFhAKZsnYlNNvp1jS_Aw',
    appId: '1:666637684350:ios:1da669dbf7be019916522f',
    messagingSenderId: '666637684350',
    projectId: 'the-expenses-718d1',
    storageBucket: 'the-expenses-718d1.appspot.com',
    iosBundleId: 'com.example.theExpenses.RunnerTests',
  );
}
